### ISSUE TITLE
`quark up` should not complain if the current folder is not versioned

### ISSUE THREAD

**Issue by naufraghi** [comelz/quark#2]
Our use case is to replicate a nested project structure in a project folder (not versioned as a repo itself, but in a versioned repo, but that may not be the case).

```
quark.subproject.QuarkError: Couldn't detect repository type for directory
```

An option can be useful to unlock different usage scenarios (both to opt out or IMHO opt in)

**Comment by cvtsi2sd** [comment]
Implemented in #6 . Call `quark up` with `-d` (or `--deps-only`) and it'll ignore the root project VCS stuff completely.
