### ISSUE TITLE
Do not fetch if the local commit matches the frozen one

### ISSUE THREAD

**Issue by naufraghi** [comelz/quark#45]
This should allow caching of the `lib/` folder and limit extra network access

**Comment by naufraghi** [comment]
In fact it does already the correct thing, what was failing was an unwanted `stash` because of some modified files.

`git stash` needs a valid user and emal

**Comment by cvtsi2sd** [comment]
Luckily it seems like this has been fixed in more recent git versions. If that's a problem on CI, though, we may add a workaround like in the accepted answer there.
